-- ============================================================
-- SSR SYSTEM — MIGRATION 004: CORE TABLES
-- Solapur Smart Roads — रोड NIRMAN
-- ============================================================
-- User profiles, tickets (the heart of the system),
-- audit trail, contractor billing, and performance metrics.
-- ============================================================


-- ============================================================
-- 4A: USER PROFILES (Extends Supabase Auth)
-- Every authenticated user gets a profile row.
-- Role determines interface routing (Citizen/JE/Contractor mode).
-- OPI tracking fields for officer accountability.
-- ============================================================

CREATE TABLE profiles (
  id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name       TEXT NOT NULL,
  phone           VARCHAR(15) UNIQUE,
  email           TEXT,
  role            user_role NOT NULL DEFAULT 'citizen',
  zone_id         INT REFERENCES zones(id),          -- For JE, DE, Asst Commissioner
  department_id   INT REFERENCES departments(id) DEFAULT 1,  -- Default: Roads
  employee_id     VARCHAR(20),                       -- SMC employee code
  designation     TEXT,                              -- "Junior Engineer", "Deputy Engineer"
  is_active       BOOLEAN DEFAULT true,
  fcm_token       TEXT,                              -- Firebase Cloud Messaging token
  -- OPI (Officer Performance Index) tracking
  opi_score       FLOAT,                             -- Auto-calculated monthly (0–100)
  opi_zone        VARCHAR(10),                       -- 'green' (>85%), 'yellow' (60–85%), 'red' (<60%)
  opi_last_computed TIMESTAMPTZ,
  -- Timestamps
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE profiles IS 'User profiles extending Supabase Auth. Role determines app mode and dashboard access.';
COMMENT ON COLUMN profiles.opi_score IS 'Officer Performance Index: (Resolved within SLA / Total Assigned) × 100. Green >85%, Yellow 60-85%, Red <60%.';


-- ============================================================
-- 4B: CONTRACTOR DETAILS (Extends profiles for contractor role)
-- Empaneled firms under Annual Maintenance Contract.
-- ============================================================

CREATE TABLE contractors (
  id                UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  company_name      TEXT NOT NULL,                    -- "S.S. Ekbote Construction"
  company_name_marathi TEXT,
  gst_number        VARCHAR(15),
  pan_number        VARCHAR(10),
  zone_ids          INT[],                            -- Zones they hold AMC for
  contract_number   TEXT,                             -- AMC contract reference
  contract_start    DATE,
  contract_end      DATE,
  is_blacklisted    BOOLEAN DEFAULT false,
  blacklist_reason  TEXT,
  blacklist_date    TIMESTAMPTZ,
  defect_flags      INT DEFAULT 0,                   -- 3 flags → blacklisted
  created_at        TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE contractors IS 'Empaneled contractor firms. Annual Maintenance Contract. 3 defect flags = blacklisted.';
COMMENT ON COLUMN contractors.defect_flags IS 'Incremented when defect liability triggered (recompaint within 50m + 6 months). 3 flags → auto-blacklist.';


-- ============================================================
-- 4C: TICKETS — THE CORE TABLE
-- Every road damage complaint lives here.
-- Captures the full lifecycle from citizen photo to contractor payment.
-- 
-- Field groups:
--   Identity → Reporter → Location → Damage Classification →
--   AI Analysis → Evidence → Workflow → JE Verification →
--   SSIM Verification → Billing → Resolution → Dedup → Accountability
-- ============================================================

CREATE TABLE tickets (
  -- ── IDENTITY ──────────────────────────────────────────────
  id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_ref          TEXT UNIQUE,                    -- "SSR-Z4-P12-2025-0089" (auto-generated by trigger)
  created_at          TIMESTAMPTZ DEFAULT now(),
  updated_at          TIMESTAMPTZ DEFAULT now(),

  -- ── REPORTER ──────────────────────────────────────────────
  citizen_id          UUID REFERENCES auth.users(id),
  citizen_phone       VARCHAR(15),                    -- For WhatsApp/OTP citizens
  citizen_name        TEXT,                           -- Optional display name
  source_channel      TEXT DEFAULT 'app',             -- 'app', 'whatsapp', 'portal', 'phone', 'walk_in'

  -- ── LOCATION (GPS-first — O2, O7) ─────────────────────────
  location            GEOGRAPHY(POINT, 4326) NOT NULL,
  latitude            FLOAT NOT NULL,
  longitude           FLOAT NOT NULL,
  address_text        TEXT,                           -- Reverse geocoded address
  nearest_landmark    TEXT,                           -- From SMC 600+ landmark list
  road_name           TEXT,                           -- "Akkalkot Road", "NH-65"
  prabhag_id          INT REFERENCES prabhags(id),   -- Auto-filled by trigger (GPS → Prabhag)
  zone_id             INT REFERENCES zones(id),       -- Auto-filled by trigger (Prabhag → Zone)

  -- ── DAMAGE CLASSIFICATION ──────────────────────────────────
  damage_type         TEXT,                           -- 'pothole', 'crack', 'surface_failure', 'cave_in'
  damage_cause        damage_cause,                  -- AI-suggested + JE-confirmed
  department_id       INT REFERENCES departments(id) DEFAULT 1,  -- Default: Roads
  department_note     TEXT,                           -- JE note on cross-assignment reason

  -- ── AI ANALYSIS (O5, O6) ───────────────────────────────────
  ai_confidence       FLOAT,                         -- YOLOv8 confidence 0.0–1.0
  ai_severity_index   FLOAT,                         -- SAI component of EPDO (0–1)
  epdo_score          FLOAT,                         -- Final EPDO 0–10
  severity_tier       severity_tier,                 -- CRITICAL/HIGH/MEDIUM/LOW
  rainfall_risk       FLOAT,                         -- From IMD API at time of report
  road_class          TEXT,                          -- 'arterial', 'collector', 'local', etc.
  proximity_score     FLOAT,                         -- Distance to hospital/school/highway (0–1)
  total_potholes      INT,                           -- Count from YOLOv8 bounding boxes
  ai_source           TEXT DEFAULT 'YOLO_REAL',      -- 'YOLO_REAL' or 'OFFLINE_ESTIMATE'
  ai_bounding_boxes   JSONB,                         -- Raw bounding box data from YOLO

  -- ── EVIDENCE (O4, O30) ──────────────────────────────────────
  photo_before        TEXT[],                        -- Array: up to 3 before photos (Supabase Storage URLs)
  photo_after         TEXT,                          -- Single verified after photo
  photo_je_inspection TEXT,                          -- JE's site inspection photo

  -- ── WORKFLOW STATUS ─────────────────────────────────────────
  status              ticket_status DEFAULT 'open',
  assigned_je         UUID REFERENCES auth.users(id),
  assigned_contractor UUID REFERENCES auth.users(id),
  assigned_mukadam    UUID REFERENCES auth.users(id),
  approval_tier       approval_tier,                 -- Computed from estimated_cost

  -- ── JE VERIFICATION DATA (O36, O37) ─────────────────────────
  je_checkin_lat      FLOAT,
  je_checkin_lng      FLOAT,
  je_checkin_time     TIMESTAMPTZ,
  je_checkin_distance_m FLOAT,                       -- Distance from reported point (must be ≤20m)
  dimensions          JSONB,
  -- {"length_m": 2.5, "width_m": 1.5, "depth_m": 0.1, "area_sqm": 3.75}
  work_type           TEXT,                          -- Selected from rate_cards.work_type
  rate_card_id        UUID REFERENCES rate_cards(id),
  rate_per_unit       NUMERIC(10,2),                 -- Locked at time of verification (immutable)
  estimated_cost      NUMERIC(10,2),                 -- Auto-calculated = area × rate (immutable after JE approval)
  job_order_ref       TEXT UNIQUE,                   -- "JO-Z4-P12-2025-0089"

  -- ── SSIM VERIFICATION (O32, O33) ────────────────────────────
  ssim_score          FLOAT,                         -- 0.0–1.0 (INVERSE: <0.75 = PASS)
  ssim_pass           BOOLEAN,                       -- score < 0.75 = surface changed = PASS
  verification_hash   VARCHAR(64),                   -- SHA-256 of verified after photo
  verified_at         TIMESTAMPTZ,

  -- ── BILLING ─────────────────────────────────────────────────
  bill_id             UUID,                          -- FK added later after contractor_bills exists

  -- ── RESOLUTION ──────────────────────────────────────────────
  resolved_at         TIMESTAMPTZ,
  resolved_in_hours   FLOAT,                         -- Computed on resolution
  escalation_count    INT DEFAULT 0,
  sla_breach          BOOLEAN DEFAULT false,
  warranty_expiry     DATE,                          -- 6 months after resolved_at (defect liability)

  -- ── CITIZEN FEEDBACK (Rule 6: SMS YES/NO) ────────────────────
  citizen_confirmed   BOOLEAN,                       -- SMS response: true=YES, false=NO
  citizen_confirm_at  TIMESTAMPTZ,
  citizen_rating      INT CHECK (citizen_rating BETWEEN 1 AND 5),  -- Star rating

  -- ── DUPLICATE HANDLING (O8: 50m Haversine dedup) ─────────────
  is_duplicate        BOOLEAN DEFAULT false,
  master_ticket_id    UUID REFERENCES tickets(id),

  -- ── CHRONIC LOCATION FLAG (Rule 7) ──────────────────────────
  is_chronic_location BOOLEAN DEFAULT false,
  chronic_location_id UUID REFERENCES chronic_locations(id),

  -- ── OPI TRACKING ────────────────────────────────────────────
  opi_breach_level    INT DEFAULT 0                  -- 0=none, 1=L1(DE), 2=L2(AC), 3=L3(CE)
);

COMMENT ON TABLE tickets IS 'Core complaint table. Every road damage report lives here. Lifecycle: open → verified → assigned → in_progress → audit_pending → resolved.';
COMMENT ON COLUMN tickets.ssim_pass IS 'INVERSE SSIM: score < 0.75 means surface CHANGED (repair verified). score >= 0.75 means surface UNCHANGED (repair failed).';
COMMENT ON COLUMN tickets.warranty_expiry IS '6 months after resolved_at. New complaint within 50m before expiry triggers defect liability on contractor.';
COMMENT ON COLUMN tickets.approval_tier IS 'Auto-computed: <₹50K = minor (JE direct), ₹50K-5L = moderate (SE→EE), >₹5L = major (Commissioner chain).';


-- ============================================================
-- 4D: TICKET EVENTS — IMMUTABLE AUDIT TRAIL (O38)
-- Every state transition, assignment, escalation, photo upload,
-- SSIM result, and bill generation is logged here.
-- INSERT-only: No UPDATE or DELETE ever.
-- ============================================================

CREATE TABLE ticket_events (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_id   UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  actor_id    UUID REFERENCES auth.users(id),
  actor_role  user_role,
  event_type  TEXT NOT NULL,
  -- Event types:
  --   'status_change', 'assignment', 'escalation', 'cross_assign',
  --   'je_checkin', 'photo_upload', 'ssim_result', 'bill_generated',
  --   'citizen_feedback', 'dimension_input', 'rate_card_locked',
  --   'sla_breach', 'chronic_flag', 'defect_liability'
  old_status  ticket_status,
  new_status  ticket_status,
  notes       TEXT,
  metadata    JSONB,                  -- Extra context: GPS coords, scores, distances, etc.
  created_at  TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE ticket_events IS 'Immutable audit trail. INSERT-only — no UPDATE or DELETE allowed. Every action on a ticket is logged here.';


-- ============================================================
-- 4E: CONTRACTOR BILLS — DIGITAL MEASUREMENT BOOK (O29, O34)
-- Every pothole = one line item. No consolidated billing.
-- Bill can only be submitted after all ticket photos are verified.
-- ============================================================

CREATE TABLE contractor_bills (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_ref        TEXT UNIQUE,                        -- "BILL-Z4-2025-0012"
  contractor_id   UUID NOT NULL REFERENCES auth.users(id),
  zone_id         INT REFERENCES zones(id),
  fiscal_year     VARCHAR(7),
  -- Aggregates computed from bill_line_items (updated by trigger/app)
  total_tickets   INT DEFAULT 0,
  total_area_sqm  NUMERIC(10,2) DEFAULT 0,
  total_amount    NUMERIC(12,2) DEFAULT 0,
  pdf_url         TEXT,                               -- Supabase Storage URL for generated PDF
  status          bill_status DEFAULT 'draft',
  submitted_at    TIMESTAMPTZ,
  reviewed_by     UUID REFERENCES auth.users(id),     -- Accounts user
  reviewed_at     TIMESTAMPTZ,
  approved_by     UUID REFERENCES auth.users(id),     -- Final approver
  approved_at     TIMESTAMPTZ,
  payment_ref     TEXT,                               -- Cheque/NEFT reference
  payment_date    DATE,
  rejection_reason TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE contractor_bills IS 'Digital Measurement Book header. Line items are in bill_line_items. PDF auto-generated with Before/After photos, SSIM scores, and SHA-256 hashes.';

-- Add the billing link only after contractor_bills exists to avoid migration-order failure
ALTER TABLE tickets
  ADD CONSTRAINT fk_tickets_bill_id
  FOREIGN KEY (bill_id) REFERENCES contractor_bills(id);


-- ============================================================
-- 4E-2: BILL LINE ITEMS — NORMALIZED MICRO-BILLING (O29, O34)
-- Each line = one ticket (one pothole repair).
-- UNIQUE on ticket_id prevents double-billing.
-- FK-backed: contractor + zone must match the bill header.
-- ============================================================

CREATE TABLE bill_line_items (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_id         UUID NOT NULL REFERENCES contractor_bills(id) ON DELETE CASCADE,
  ticket_id       UUID NOT NULL REFERENCES tickets(id),
  work_type       TEXT NOT NULL,                      -- Matches rate_cards.work_type
  area_sqm        NUMERIC(10,2) NOT NULL,             -- From JE-measured dimensions
  rate_per_unit   NUMERIC(10,2) NOT NULL,             -- Locked from rate_cards at verification time
  line_amount     NUMERIC(10,2) NOT NULL,             -- area_sqm × rate_per_unit (immutable)
  ssim_score      FLOAT,                              -- SSIM score for this repair
  ssim_pass       BOOLEAN,                            -- SSIM verification result
  photo_before    TEXT,                                -- Supabase Storage URL
  photo_after     TEXT,                                -- Supabase Storage URL
  verification_hash VARCHAR(64),                      -- SHA-256 of after photo
  created_at      TIMESTAMPTZ DEFAULT now(),
  -- Enforce one-ticket-per-line-item across ALL bills
  CONSTRAINT uq_one_bill_per_ticket UNIQUE (ticket_id)
);

COMMENT ON TABLE bill_line_items IS 'Normalized micro-billing: one row per ticket per bill. UNIQUE on ticket_id prevents double-billing. FK-backed integrity.';
COMMENT ON COLUMN bill_line_items.line_amount IS 'Immutable: area_sqm × rate_per_unit locked at JE verification time.';

-- Index for bill lookups
CREATE INDEX idx_line_items_bill ON bill_line_items (bill_id);
CREATE INDEX idx_line_items_ticket ON bill_line_items (ticket_id);


-- ============================================================
-- 4F: CONTRACTOR PERFORMANCE METRICS (O27)
-- Powers the Vendor Scorecard on Commissioner dashboard.
-- Auto-computed from tickets — re-open rate determines contract renewal.
-- ============================================================

CREATE TABLE contractor_metrics (
  contractor_id       UUID PRIMARY KEY REFERENCES auth.users(id),
  zone_id             INT REFERENCES zones(id),
  total_assigned      INT DEFAULT 0,
  total_completed     INT DEFAULT 0,
  total_ssim_pass     INT DEFAULT 0,
  total_ssim_fail     INT DEFAULT 0,
  total_reopen        INT DEFAULT 0,           -- Tickets re-opened after "resolved"
  total_defect_flags  INT DEFAULT 0,           -- Defect liability triggers
  avg_repair_hours    FLOAT,
  ssim_pass_rate      FLOAT,                   -- ssim_pass / total_assigned
  reopen_rate         FLOAT,                   -- reopen / total_assigned (SCORECARD ranking)
  quality_index       FLOAT,                   -- Composite: SSIM pass rate × (1 - reopen rate)
  scorecard_rank      INT,                     -- Computed monthly, 1 = best
  last_computed_at    TIMESTAMPTZ
);

COMMENT ON TABLE contractor_metrics IS 'Contractor performance metrics. Vendor Scorecard: re-open rate determines annual contract renewal.';
COMMENT ON COLUMN contractor_metrics.reopen_rate IS 'Primary ranking metric for Commissioner Vendor Scorecard. Lower = better.';


-- ============================================================
-- 4G: NOTIFICATIONS LOG
-- Track all SMS/push notifications sent.
-- ============================================================

CREATE TABLE notifications (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  ticket_id       UUID REFERENCES tickets(id),
  recipient_id    UUID REFERENCES auth.users(id),
  recipient_phone VARCHAR(15),
  channel         TEXT NOT NULL,                     -- 'sms', 'push', 'whatsapp', 'email'
  template_key    TEXT,                              -- 'verified', 'in_progress', 'resolved', etc.
  message_text    TEXT,
  status          TEXT DEFAULT 'pending',            -- 'pending', 'sent', 'delivered', 'failed'
  provider_ref    TEXT,                              -- MSG91/FCM message ID
  sent_at         TIMESTAMPTZ,
  delivered_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE notifications IS 'Log of all SMS/Push/WhatsApp notifications sent. Tracks delivery status.';
